<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE beans [

        <!ELEMENT bean ANY>      <!--bean ANY定义bean的类型-->
        <!ELEMENT beans (bean*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref IDREF #IMPLIED>

        ]>
<beans>
    <bean id="userBasicDAO" class="com.atguigu.qqzone.dao.impl.UserBasicDAOImpl"></bean>
    <bean id="topicDAO" class="com.atguigu.qqzone.dao.impl.TopicDAOImpl"></bean>
    <bean id="replyDAO" class="com.atguigu.qqzone.dao.impl.ReplyDAOImpl"></bean>
    <bean id="hostReplyDAO" class="com.atguigu.qqzone.dao.impl.hostReplyDAOImpl"></bean>


    <bean id="userBasicService" class="com.atguigu.qqzone.service.impl.UserBasicServiceImp">
        <property name="userBasicDAO" ref="userBasicDAO"></property>
    </bean>
    <bean id="topicService" class="com.atguigu.qqzone.service.impl.TopicServiceImpl">
        <property name="topicDAO" ref="topicDAO"></property>
        <property name="replyService" ref="replyService"></property>
        <property name="userBasicService" ref="userBasicService"></property>
    </bean>
    <bean id="hostReplyService" class="com.atguigu.qqzone.service.impl.HostReplyServiceImpl">
        <property name="hostReplyDAO" ref="hostReplyDAO"></property>
    </bean>
    <bean id="replyService" class="com.atguigu.qqzone.service.impl.ReplyServiceImpl">
        <property name="replyDAO" ref="replyDAO"></property>
        <property name="hostReplyService" ref="hostReplyService"></property>
        <property name="userBasicService" ref="userBasicService"></property>
    </bean>


    <bean id="user" class="com.atguigu.qqzone.controller.UserController">
        <property name="userBasicService" ref="userBasicService"></property>
        <property name="topicService" ref="topicService"></property>
    </bean>
    <bean id="page" class="com.atguigu.myssm.myspringmvc.PageController"></bean>
    <bean id="topic" class="com.atguigu.qqzone.controller.TopicController">
        <property name="topicService" ref="topicService"></property>
        <property name="replyService" ref="replyService"></property>
    </bean>
    <bean id="reply" class="com.atguigu.qqzone.controller.ReplyController">
        <property name="replyService" ref="replyService"></property>
        <property name="hostReplyService" ref="hostReplyService"></property>
    </bean>
</beans>